version : "3.0"
services:
  web:
    build: .
    user: root
    ports:
      - "8080:8080"
    container_name: JenkinsQuick
    volumes:
       - /home/ubuntu/Mounted:/root/app/
      #      - /var/run/docker.sock:/var/run/docker.sock
